var listSongs = [
    "AdeleVEVO.Adele - Easy On Me (Official Video).mp3",
    "AdeleVEVO.Adele - Hello.mp3",
    "AdeleVEVO.Adele - Rolling in the Deep (Official Music Video).mp3",
    "ArianaGrandeVevo.Ariana Grande - positions (official video).mp3",
    "BENNETT.BENNETT - When It\'s Too Good [Official Music Video].mp3",
    "BLACKPINK.BLACKPINK - \'Ice Cream (with Selena Gomez)\' M_V.mp3",
    "BeyoncéVEVO.Beyoncé - Halo.mp3",
    "Bruno Mars.Bruno Mars - Locked Out Of Heaven (Official Music Video).mp3",
    "Bruno Mars.Bruno Mars - The Lazy Song (Official Music Video).mp3",
    "Bruno Mars.Bruno Mars - When I Was Your Man (Official Music Video).mp3",
    "CalumScottVEVO.Calum Scott - You Are The Reason (Official Video).mp3",
    "Charlie Puth.Charlie Puth - We Don\'t Talk Anymore (feat. Selena Gomez) [Official Video].mp3",
    "Clean Bandit.Clean Bandit - Rockabye (feat. Sean Paul & Anne-Marie) [Official Video].mp3",
    "Coldplay.Coldplay X BTS - My Universe (Official Video).mp3",
    "DJSnakeVEVO.DJ Snake - Let Me Love You ft. Justin Bieber (Official Video).mp3",
    "Dan And Shay.Dan + Shay - Steal My Love (Official Music Video).mp3",
    "Dua Lipa.Dua Lipa - New Rules (Official Music Video).mp3",
    "ELYAZ.ELYAZ - Remember Home (Official Video).mp3",
    "Ed Sheeran.Ed Sheeran - Bad Habits [Official Video].mp3",
    "Ed Sheeran.Ed Sheeran - Perfect (Official Music Video).mp3",
    "Ed Sheeran.Ed Sheeran - Shape of You (Official Music Video).mp3",
    "Ed Sheeran.Ed Sheeran - Shivers [Official Video].mp3",
    "Ella Henderson.Ella Henderson - Brave.mp3",
    "EltonJohnVEVO.Elton John, Dua Lipa - Cold Heart (PNAU Remix) (Official Video).mp3",
    "FifthHarmonyVEVO.Fifth Harmony - Work from Home (Official Video) ft. Ty Dolla $ign.mp3",
    "HarryStylesVEVO.Harry Styles - Sign of the Times (Official Video).mp3",
    "JustinBieberVEVO.Justin Bieber - Ghost.mp3",
    "JustinBieberVEVO.Justin Bieber - Intentions (Official Video (Short Version)) ft. Quavo.mp3",
    "KatyPerryVEVO.Alesso, Katy Perry - When I\'m Gone (Official Music Video).mp3",
    "KatyPerryVEVO.Katy Perry - Dark Horse (Official) ft. Juicy J.mp3",
    "KatyPerryVEVO.Katy Perry - Roar (Official).mp3",
    "LadyGagaVEVO.Lady Gaga - Bad Romance (Official Music Video).mp3",
    "LadyGagaVEVO.Lady Gaga - Poker Face (Official Music Video).mp3",
    "LadyGagaVEVO.Lady Gaga, Bradley Cooper - Shallow (from A Star Is Born) (Official Music Video).mp3",
    "Lukas Graham.Lukas Graham - 7 Years [Official Music Video].mp3",
    "MarkRonsonVEVO.Mark Ronson - Uptown Funk (Official Video) ft. Bruno Mars.mp3",
    "Maroon5VEVO.Maroon 5 - Girls Like You ft. Cardi B (Official Music Video).mp3",
    "Maroon5VEVO.Maroon 5 - Sugar (Official Music Video).mp3",
    "Marshmello.Marshmello ft. Bastille - Happier (Official Music Video).mp3",
    "MattCooperVEVO.Matt Cooper - Taylor Swift (Official Music Video).mp3",
    "Noa Kirel.Noa Kirel - Thought About That (Official Music Video).mp3",
    "Passenger.Passenger _ Let Her Go (Official Video).mp3",
    "SeanPaulVEVO.Sean Paul - No Lie ft. Dua Lipa.mp3",
    "ShawnMendesVEVO.Shawn Mendes - There's Nothing Holdin Me Back.mp3",
    "ShawnMendesVEVO.Shawn Mendes, Camila Cabello - Señorita.mp3",
    "SiaVEVO.Sia - Cheap Thrills (Performance Edit).mp3",
    "TheKidLAROIVEVO.The Kid LAROI, Justin Bieber - STAY (Official Video).mp3",
    "johnlegendVEVO.John Legend - All of Me (Official Video).mp3",
    "justintimberlakeVEVO.Justin Timberlake - Mirrors (Official Video).mp3",
    "ournameismagicVEVO.MAGIC! - Rude (Official Video).mp3"
];
listImg=[
    "AdeleVEVO.Adele - Easy On Me (Official Video).webp",
"AdeleVEVO.Adele - Hello.jpg",
"AdeleVEVO.Adele - Rolling in the Deep (Official Music Video).webp",
"ArianaGrandeVevo.Ariana Grande - positions (official video).webp",
"BENNETT.BENNETT - When It\'s Too Good [Official Music Video].webp",
"BLACKPINK.BLACKPINK - \'Ice Cream (with Selena Gomez)\' M_V.webp",
"BeyoncéVEVO.Beyoncé - Halo.webp",
"Bruno Mars.Bruno Mars - Locked Out Of Heaven (Official Music Video).jpg",
"Bruno Mars.Bruno Mars - The Lazy Song (Official Music Video).jpg",
"Bruno Mars.Bruno Mars - When I Was Your Man (Official Music Video).jpg",
"CalumScottVEVO.Calum Scott - You Are The Reason (Official Video).webp",
"Charlie Puth.Charlie Puth - We Don\'t Talk Anymore (feat. Selena Gomez) [Official Video].webp",
"Clean Bandit.Clean Bandit - Rockabye (feat. Sean Paul & Anne-Marie) [Official Video].webp",
"Coldplay.Coldplay X BTS - My Universe (Official Video).webp",
"DJSnakeVEVO.DJ Snake - Let Me Love You ft. Justin Bieber (Official Video).webp",
"Dan And Shay.Dan + Shay - Steal My Love (Official Music Video).webp",
"Dua Lipa.Dua Lipa - New Rules (Official Music Video).webp",
"ELYAZ.ELYAZ - Remember Home (Official Video).webp",
"Ed Sheeran.Ed Sheeran - Bad Habits [Official Video].webp",
"Ed Sheeran.Ed Sheeran - Perfect (Official Music Video).webp",
"Ed Sheeran.Ed Sheeran - Shape of You (Official Music Video).webp",
"Ed Sheeran.Ed Sheeran - Shivers [Official Video].webp",
"Ella Henderson.Ella Henderson - Brave.webp",
"EltonJohnVEVO.Elton John, Dua Lipa - Cold Heart (PNAU Remix) (Official Video).webp",
"FifthHarmonyVEVO.Fifth Harmony - Work from Home (Official Video) ft. Ty Dolla $ign.webp",
"HarryStylesVEVO.Harry Styles - Sign of the Times (Official Video).jpg",
"JustinBieberVEVO.Justin Bieber - Ghost.webp",
"JustinBieberVEVO.Justin Bieber - Intentions (Official Video (Short Version)) ft. Quavo.webp",
"KatyPerryVEVO.Alesso, Katy Perry - When I\'m Gone (Official Music Video).webp",
"KatyPerryVEVO.Katy Perry - Dark Horse (Official) ft. Juicy J.jpg",
"KatyPerryVEVO.Katy Perry - Roar (Official).jpg",
"LadyGagaVEVO.Lady Gaga - Bad Romance (Official Music Video).webp",
"LadyGagaVEVO.Lady Gaga - Poker Face (Official Music Video).webp",
"LadyGagaVEVO.Lady Gaga, Bradley Cooper - Shallow (from A Star Is Born) (Official Music Video).webp",
"Lukas Graham.Lukas Graham - 7 Years [Official Music Video].webp",
"MarkRonsonVEVO.Mark Ronson - Uptown Funk (Official Video) ft. Bruno Mars.webp",
"Maroon5VEVO.Maroon 5 - Girls Like You ft. Cardi B (Official Music Video).webp",
"Maroon5VEVO.Maroon 5 - Sugar (Official Music Video).webp",
"Marshmello.Marshmello ft. Bastille - Happier (Official Music Video).webp",
"MattCooperVEVO.Matt Cooper - Taylor Swift (Official Music Video).webp",
"Noa Kirel.Noa Kirel - Thought About That (Official Music Video).webp",
"Passenger.Passenger _ Let Her Go (Official Video).webp",
"SeanPaulVEVO.Sean Paul - No Lie ft. Dua Lipa.webp",
"ShawnMendesVEVO.Shawn Mendes - There's Nothing Holdin' Me Back.webp",
"ShawnMendesVEVO.Shawn Mendes, Camila Cabello - Señorita.webp",
"SiaVEVO.Sia - Cheap Thrills (Performance Edit).webp",
"TheKidLAROIVEVO.The Kid LAROI, Justin Bieber - STAY (Official Video).webp",
"johnlegendVEVO.John Legend - All of Me (Official Video).webp",
"justintimberlakeVEVO.Justin Timberlake - Mirrors (Official Video).webp",
"ournameismagicVEVO.MAGIC! - Rude (Official Video).webp"
];